### ISSUE TITLE
Unable to find mod.json

### ISSUE THREAD

**Issue by ZeTerTy** [Pixelguin/OMO-CEP-v3#2]
[latest.log](https://github.com/user-attachments/files/15654683/latest.log)

**Comment by Pixelguin** [comment]
> [ERROR] Catastrophic failure when processing OMO-CEP_13_10_1-rev1.zip! Error: Unable to find mod.json

It looks like you put the entire OMO CEP archive in your `www\mods` folder.
If you are upgrading OMO CEP, you'll need to unzip the archive and drag + drop the `www` folder as described in the [Upgrade Instructions](https://omo.cep.one/upgrade).

**Comment by ZeTerTy** [comment]
> > [ERROR] Catastrophic failure when processing OMO-CEP_13_10_1-rev1.zip! Error: Unable to find mod.json
> 
> It looks like you put the entire OMO CEP archive in your `www\mods` folder. If you are upgrading OMO CEP, you'll need to unzip the archive and drag + drop the `www` folder as described in the [Upgrade Instructions](https://omo.cep.one/upgrade).

я переделывал всё несколько раз по инструкции

**Comment by Pixelguin** [comment]
There shouldn't be any ZIP archive named `OMO-CEP_13_10_1-rev1.zip` in your game files—the game is crashing because it thinks that is a mod that it needs to load. You need to unzip that archive somewhere else, then you take the `www` folder inside and merge it with the existing `OMORI\www` game folder.

**Comment by ZeTerTy** [comment]
почему, когда я добавляю ещё и свои моды, то игра запускается вообще без всего? даже значка oneloader нет при запуске

**Comment by Pixelguin** [comment]
You might have installed it incorrectly, or it may be incompatible with OMO CEP. I'd recommend reaching out to the creator of that mod to figure it out - they're probably on the [OMORI Discord server](https://discord.gg/omori).
