### ISSUE TITLE
Look into supporting the upcoming ChowLoader on Switch

### ISSUE THREAD

**Issue by SirGamers** [Pixelguin/OMO-CEP-v3#3]
**What is this feedback about?**
This is an idea I had after I found out this was a thing
it is probably very very stupid

**Feedback**
Ok, so [one Mr. pharuxtan](https://github.com/pharuxtan) is [developing a modloader](https://github.com/chowloader) for the Switch version of the game and I was thinking *WHEN* it gets finished (prob not for a while (or at all) but still) maybe make a version of the pack for Switch??? ;)
I mean it wouldn't be ***that*** hard to port since he wants to mimic the oneloader structure (eventually)
all jokes aside tho

**Comment by Pixelguin** [comment]
I don't own the game on Switch, but when the mod loader is finished I'd be happy to look into it!

**Comment by Pixelguin** [comment]
There doesn't seem to have been any activity on the ChowLoader repository for over a month, so I'll close this issue for now. When/if it's finished, we can look into it again.
