### ISSUE TITLE
Add Emotion Particles Restoration to OMO CEP

### ISSUE THREAD

**Issue by xzi** [Pixelguin/OMO-CEP-v3#6]
**Mod page**
https://mods.one/mod/restoredparticles

**Are you the creator of this mod?**
No

**Additional context**
Haven't tested on OMO CEP yet. Will try it later... Maybe

**Comment by Pixelguin** [comment]
This mod looks really cool, but I'm not sure this would be a good fit for OMO CEP.

Content like this is usually cut for a reason, and it seems its functionality wasn't even finished in the final build. We don't want to add mods just for the sake of adding more mods, especially if they could compromise the direction intended by the game's creators.

The mod looks like it's compatible with OMO CEP, so players who want to use it can add it themselves.
